#include <stdint.h>
#include <stdbool.h>
void IRQSetMask(uint8_t IRQline, bool status);
extern void IRQ0();
extern void IRQ1();
extern void IRQ2();
extern void IRQ3();
extern void IRQ4();
extern void IRQ5();
extern void IRQ6();
extern void IRQ7();
extern void IRQ8();
extern void IRQ9();
extern void IRQ10();
extern void IRQ11();
extern void IRQ12();
extern void IRQ13();
extern void IRQ14();
extern void IRQ15();
extern void IRQ16();
extern void IRQ17();
extern void IRQ18();
extern void IRQ19();
extern void IRQ20();
extern void IRQ21();
extern void IRQ22();
extern void IRQ23();
extern void IRQ24();
extern void IRQ25();
extern void IRQ26();
extern void IRQ27();
extern void IRQ28();
extern void IRQ29();
extern void IRQ30();
extern void IRQ31();